Project
stepancar-web-programming/2022-fall-lab-portfolio-suvorov-denis-vitalevich pull request #4
Opened 2022-12-10 23:34 UTC by Erkobrax

2022-12-17 03:39 UTC, stepancar requested changes
1

2022-12-17 03:42 UTC, stepancar commented on .idea/.gitignore
> +# Default ignored files
Пожалйста, положите в корень обычный .gitignore

файлы от IDE коммитить не нужно.

2022-12-17 03:43 UTC, stepancar commented on index.js
> +// }
Пожалуйста, убедитесь в том что код готов к ревью перед созданием ПР

2022-12-17 03:44 UTC, stepancar commented on package-lock.json
> +  "name": "2022-fall-lab-portfolio-suvorov-denis-vitalevich_",
по какой-то причине package.json в ПР нет, при этом есть package.lock

2022-12-17 03:44 UTC, stepancar commented on index.js
> +    setTimeout(showSlides, 5000)
пожалуйста, убедитесь что в том что код проверен линтерами перед отправкой на ревью

2022-12-17 15:37 UTC, Erkobrax commented on .idea/.gitignore
> +# Default ignored files
Исправил

2022-12-17 15:37 UTC, Erkobrax commented on index.js
> +// }
Исправил

2022-12-17 15:37 UTC, Erkobrax commented on package-lock.json
> +  "name": "2022-fall-lab-portfolio-suvorov-denis-vitalevich_",
Исправил

2022-12-17 15:38 UTC, Erkobrax commented on index.js
> +    setTimeout(showSlides, 5000)
Проверил

2022-12-17 15:46 UTC, Erkobrax commented on .idea/.gitignore
> +# Default ignored files
@stepancar

2022-12-18 01:58 UTC, stepancar commented on .idea/2022-fall-lab-portfolio-suvorov-denis-vitalevich-1.iml
> +<module type="JAVA_MODULE" version="4">
?

2022-12-18 02:01 UTC, stepancar commented on style.css
> +}
Не ясна мотивация использования Id вместо классов

2022-12-18 02:02 UTC, stepancar commented on style.css
> +}
Пожалуйста, убедитесь что код проверен линтером перед отправкой на ревью

2022-12-18 02:02 UTC, stepancar commented on style.css
> +/*}*/
Пожалуйста, убедитесь что код готов к ревью перед созданием ПР

2022-12-18 02:02 UTC, stepancar commented on style.css
> +.container_contacts{
Микс паттернов именования

2022-12-18 02:05 UTC, stepancar commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
не понятна мотивация использования 1 логики вместо 0 логики, если вы потом всеравно конвертируете к 0

2022-12-18 07:43 UTC, Erkobrax commented on .idea/2022-fall-lab-portfolio-suvorov-denis-vitalevich-1.iml
> +<module type="JAVA_MODULE" version="4">
А я же удалил .idea с гита

2022-12-18 09:52 UTC, Erkobrax commented on style.css
> +}
Переделал

2022-12-18 09:52 UTC, Erkobrax commented on style.css
> +}
проверил

2022-12-18 09:52 UTC, Erkobrax commented on style.css
> +/*}*/
исправил

2022-12-18 09:52 UTC, Erkobrax commented on style.css
> +.container_contacts{
исправил

2022-12-18 09:58 UTC, Erkobrax commented on style.css
> +}
Якоря для меню

2022-12-18 10:00 UTC, Erkobrax commented on style.css
> +.container_contacts{
исправил

2022-12-18 10:47 UTC, Erkobrax commented on .idea/2022-fall-lab-portfolio-suvorov-denis-vitalevich-1.iml
> +<module type="JAVA_MODULE" version="4">
![image](https://user-images.githubusercontent.com/69597295/208294035-330bec20-5930-4c48-a5b2-2b741436863d.png)

2022-12-23 09:59 UTC, Erkobrax commented on style.css
> +.container_contacts{
@stepancar

2022-12-26 00:44 UTC, stepancar commented on video.html
> +    <a href="javascript:void(0);" class="icon" onclick="myFunction()"></a>
не вижу где объявлена функция myFunction

2022-12-26 00:46 UTC, stepancar commented
<img width="1439" alt="Screen Shot 2022-12-25 at 4 45 59 PM" src="https://user-images.githubusercontent.com/2854910/209486520-d4d4e524-07af-44a1-9d41-fa1e767e666a.png">
Фотографии растягиваются по обоим измерениям. Это приводит к таким неприятным эффектам

2022-12-26 03:29 UTC, Erkobrax commented on video.html
> +    <a href="javascript:void(0);" class="icon" onclick="myFunction()"></a>
Этой строчки вообще не должно быть
Я удалил myFunction

2022-12-26 03:32 UTC, Erkobrax commented
Я могу хорошие фотографии найти или эту удалить, оно же так, потому что разрешение фото не подошло( мне показалась такая фотография забавной)

2022-12-26 04:09 UTC, stepancar commented
> Я могу хорошие фотографии найти или эту удалить, оно же так, потому что разрешение фото не подошло( мне показалась такая фотография забавной)

К фоторграфиям не вопросов. проблема в коде. ваши фотографии тянутся на ширину контейнера, а высота фиксирована. Попробуйте порасширять окно браузера и увидите

2022-12-26 04:10 UTC, stepancar commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
@Erkobrax жду исправлений

2022-12-26 04:11 UTC, stepancar commented on video.html
> +    <a href="javascript:void(0);" class="icon" onclick="myFunction()"></a>
@Erkobrax не очень понимаю. Если вы удалили, удалите и использование?

2022-12-26 04:12 UTC, stepancar commented on style.css
> +#dog_name {
не ясна мотивация использования id

2022-12-26 04:13 UTC, stepancar commented on style.css
> +#description {
не ясна мотивация использования id

2022-12-26 04:13 UTC, stepancar commented on style.css
> +.container_contacts{
@Erkobrax  извините, я не вижу исправления

2022-12-26 05:39 UTC, Erkobrax commented on style.css
> +#description {
исправил

2022-12-26 13:03 UTC, Erkobrax commented on video.html
> +    <a href="javascript:void(0);" class="icon" onclick="myFunction()"></a>
Я запушил эти изменения уже

2022-12-28 02:03 UTC, Erkobrax commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
@stepancar исправил

2022-12-28 12:32 UTC, Erkobrax commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
Я не понимаю, каких исправлений, я просмотрел, примеры, как сделать слайдер, я посмотрел лабы других ребят у них такая же логика, как и здесь

2022-12-28 13:07 UTC, Erkobrax commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
мы сравнием с размером/длинной массива индекс, поэтому он +1, а когда обращаемся к элемантам, то отнимаем 1, потому что элемент начинается с 0

2022-12-28 13:08 UTC, Erkobrax commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
У меня изначально в самом первым пуше такая же логика

2022-12-28 13:14 UTC, Erkobrax commented
По поводу фотографий
Я изначально делал из размера auto, но тк они были разного разрешения, то этот блок очень сильно растягивало и я решил сделать размеры картинок постоянными, но забыл про то, что это не будет работать при изменении размера окна браузера

2022-12-28 13:36 UTC, Erkobrax commented on style.css
> +#dog_name {
исправил

2022-12-28 19:02 UTC, Erkobrax commented on index.js
> +  slides[slideIndex - 1].style.display = 'block';
@stepancar разобрался в том, что нужно было изменить
Изначально не мог понять, что не так 
Для меня было бы сразу понятнее, если бы написали, что в строке   slides[slideIndex - 1].style.display = 'block';
Мы используем индекс для обращения к элементу и "-1" не совсем понятен, нужно изменить код так, чтобы мы использовали slideIndex в этой строке без каких-либо других операций

2022-12-28 19:05 UTC, stepancar approved these changes

2022-12-28 19:08 UTC, stepancar commented
не забудьте вмержить

2022-12-28 20:45 UTC, merged